target-version = "py39"
line-length = 109
lint.select = ["E", "F", "I", "Q", "UP"]
# E501: line-too-long
# E731: lambda-assignment
lint.ignore = ["E501"]

[format]
# The formatter prefers double quotes for multiline quotes,
# Hence, let's make the formatter not change quotations.
quote-style = "preserve"

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
